# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and lockfile
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy application source
COPY src ./src
COPY start-mcp.sh ./start-mcp.sh
RUN chmod +x ./start-mcp.sh

# Use non-root user if desired (optional)
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

# Set entrypoint
ENTRYPOINT ["node", "src/index.js"]
